### ISSUE TITLE
make the damn thing work 

### ISSUE THREAD

**Issue by 0x00002152** [0x00002152/docker-volume-ipfs#1]
add compose file
```
version: "3.8"

services:
  ipfs-docker-plugin:
    environment:
      IPFS_PATH: /ipfs-repo
      LANG: en_US.utf8
      TZ: UTC
    build:
      context: ./ipfs/
      dockerfile: Dockerfile
    hostname: ipfs-docker-plugin
    domainname: ipfs.internal
    command: bash -c "ipfs init ; /usr/local/bin/docker-volume-ipfs -mount /ipfs"
    privileged: true
    devices:
      - /dev/fuse:/dev/fuse:rwm
    volumes:
      - /run/docker/plugins:/run/docker/plugins
      - /srv/ipfs/0/ipns:/ipns
      - /srv/ipfs/0/ipfs:/ipfs
      - /srv/ipfs/0/.ipfs:/ipfs-repo
      - /var/lib/docker/volumes:/var/lib/docker-volumes
```

starts but 

```
docker logs -f 93f156ea8efc
initializing IPFS node at /ipfs-repo
Error: ipfs configuration file already exists!
Reinitializing would overwrite your keys.

IPFS > Initializing daemon...
IPFS > go-ipfs version: 0.5.0-rc4-116999a19
IPFS > Repo version: 9
IPFS > System version: amd64/linux
IPFS > Golang version: go1.13.10
IPFS > Swarm listening on /ip4/127.0.0.1/tcp/4001
IPFS > Swarm listening on /ip4/192.168.128.226/tcp/4001
IPFS > Swarm listening on /p2p-circuit
IPFS > Swarm announcing /ip4/127.0.0.1/tcp/4001
IPFS > Swarm announcing /ip4/192.168.128.226/tcp/4001
IPFS > Swarm announcing /ip4/82.102.20.175/tcp/26121
IPFS > API server listening on /ip4/127.0.0.1/tcp/5001
IPFS > WebUI: http://127.0.0.1:5001/webui
IPFS > IPFS mounted at: /ipfs
IPFS > IPNS mounted at: /ipns
IPFS > Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
IPFS > Daemon is ready
Get {aa37fa488e1705cbd4a695729981d3e6952770988aad53212d1098f558d3e8c1 map[]}
Create {aa37fa488e1705cbd4a695729981d3e6952770988aad53212d1098f558d3e8c1 map[]}
Error /ipfs/aa37fa488e1705cbd4a695729981d3e6952770988aad53212d1098f558d3e8c1 lstat /ipfs/aa37fa488e1705cbd4a695729981d3e6952770988aad53212d1098f558d3e8c1: no such file or directory

```

```
ocker volume create --driver=ipfs  
Error response from daemon: create aa37fa488e1705cbd4a695729981d3e6952770988aad53212d1098f558d3e8c1: VolumeDriver.Create: Error while looking for volumePath /ipfs/aa37fa488e1705cbd4a695729981d3e6952770988aad53212d1098f558d3e8c1: lstat /ipfs/aa37fa488e1705cbd4a695729981d3e6952770988aad53212d1098f558d3e8c1: no such file or directory
```

```
Apr 26 02:26:53 linux-zoxo dockerd[865]: time="2020-04-26T02:26:53.636538340Z" level=error msg="Handler for POST /v1.40/volumes/create returned error: create aa37fa488e1705cbd4a695729981d3e6952770988aad53212d1098f558d3e8c1: VolumeDriver.Create: Error while looking for volumePath /ipfs/aa37fa488e1705cbd4a695729981d3e6952770988aad53212d1098f558d3e8c1: lstat /ipfs/aa37fa488e1705cbd4a695729981d3e6952770988aad53212d1098f558d3e8c1: no such file or directory"
```
